### ISSUE TITLE
Layout Problems (Containers)

### ISSUE THREAD

**Issue by aschbacd** [davidkroell/docker2go#5]
Dear docker2go development team,

recently I discovered 2 issues regarding the app layout.
First there is an issue with the container view where the text is overlapping.

![docker2go_issue_01](https://user-images.githubusercontent.com/29520376/51345883-74e69680-1a9c-11e9-821e-6c42afdaa748.jpg)

Also when I scroll down and the app bar shrinks there is a white space on the bottom of the scroll view.

![docker2go_issue_02](https://user-images.githubusercontent.com/29520376/51345942-a2334480-1a9c-11e9-84e9-9131e36f16b5.jpg)

Nevertheless thanks for creating such a powerful mobile app for docker.
I really appreciate the work you put in creating this app.

Cheers to the team!

**Comment by davidkroell** [comment]
Thanks for addressing this issues!
The first issue is currently under development and is going to be fixed in the next minor version (1.1).

The second problem is because of our layout design. There is a Fragment displayed inside an Activity. This problem occures only when you scroll in the Activity. Wenn you scroll in the white parts (fragment) the top bar does not disappear. We currently do not know how to scroll the top bar away when scrolling the fragment.

I am not sure if this is going to be fixed in next minor version.
We would be happy if you could tell us how to achive the scroll effect.
We liked to implement a WhatApp-like scroll effect.

Best regards
David Kröll

**Comment by davidkroell** [comment]
Fixed in https://github.com/davidkroell/docker2go/commit/1b2173b0f7d857d6353032bb894f4f12114ea084
